[WIX]
WIX_CLIENT_ID="foo_bar"
CLIENT_ID="foo_bar"
CLIENT_SECRET="foo_bar"
OPENAI_CODE="foo_bar"

[FASTAPI]
AUTH=false
BEARER_TOKEN="foo_bar"
MIDDLEWARE_SECRECT_KEY="foo_bar"

[EDGE_FUNCTIONS]
END_POINT = "foo_bar"
BEARER_TOKEN = "foo_bar"
EMAIL = "foo_bar"
PASSWORD = "foo_bar"
X_REGION = "foo_bar"
